session_booking/urls.py
from django.contrib import admin
from django.urls import path, include  # Import include

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='base.html'), name='adminlogin'),
    path('admin_login/', include('admin_panel.urls')),  
    path('user_login/', include('user_panel.urls')),# Include admin_panel URLs
]

user_panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name="login_view"),
    path('user_dashboard/<str:username>/', views.user_dashboard, name='user_dashboard'),
    path('book_session', views.book_session, name='book_session'),
    
]

admin_panel/models.py
from django.db import models
from django.utils import timezone

import datetime

class Session(models.Model):
    
    subject = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)
    status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
    created_at=models.DateTimeField(auto_now_add=True)
    # Add more fields like tutor name, location, etc., as needed
    
    class Meta:
        db_table = "Session"


    def __str__(self):
        return f"{self.subject} session on {self.date} at {self.time}"


class CustomUser(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
    created_at=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = "CustomUser"
    
    def __str__(self) :
        return self.name

templates/admin_templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        body {
            background-color: #9bb6d1;
        }

        .container {
            margin-top: 150px;
        }

        td {
            padding: 30px;
        }

        /* Add more custom styles as needed */
    </style>

</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <center>
                    <table>
                        <tr>
                            <td>
                                <a href="/admin_login/create_user" class="btn btn-primary">Create User</a>
                            </td>
                            <td>
                                <a href="/admin_login/create_session" class="btn btn-secondary">Create Session</a>
                            </td>
                        </tr>
                    </table>
                </center>
            </div>
        </div>
    </div>
</body>


</html>

templates/admin_templates/create_session.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create Session</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" />
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
    <br>
    &nbsp;&nbsp;&nbsp;<a href="/admin_login/" class="btn btn-primary">Back to admin home</a>
    &nbsp;&nbsp;&nbsp;<a href="/" class="btn btn-primary">Back to home</a>
    <center>
        <h1>Create Session</h1>

        <form method="post">
            {% csrf_token %}
            <label for="id_subject">Subject:</label>
            <input type="text" id="id_subject" name="subject" value="{{ form.subject.value }}">
            <br><br>
            <label for="id_date">Date:</label>
            <input type="date" id="id_date" name="date" value="{{ form.date.value }}">
            <br><br>
            <label for="id_time">Time:</label>
            <input type="time" id="id_time" name="time" value="{{ form.time.value }}">
            <br><br>
            <button type="submit">Save Session</button>
        </form>
        
    </center>

    <hr>

    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Subject</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
                {% for session in more_session %}
                <tr>
                    <td><input type="checkbox" class="checkthis" /></td>
                    <td>{{ session.id }}</td>
                    <td>{{ session.subject }}</td>
                    <td>{{ session.date }}</td>
                    <td>{{ session.time }}</td>
                    <td>{{ session.status }}</td>
                    <td>{{ session.created_at }}</td>
                    <td><a href="/admin_login/session_edit/{{ session.id }}" class="btn btn-primary">Edit</a></td>
                    <td><a href="/admin_login/session_delete/{{ session.id }}" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#bootstrapdatatable').DataTable({
                "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
                "iDisplayLength": 3
            }
            );
        });
    </script>

</body>

</html>

templates/admin_templates/create_user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" />
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
    <br>
    &nbsp;&nbsp;&nbsp;<a href="/admin_login/" class="btn btn-primary">Back to admin home</a>
    &nbsp;&nbsp;&nbsp;<a href="/" class="btn btn-primary">Back to home</a>
    <center>
        <h1>Create User</h1>
        
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- Render form fields -->
            <button type="submit">Save User</button>
        </form>
    </center>

    <hr>

    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>User Name</th>
                <th>Password</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td><input type="checkbox" class="checkthis" /></td>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.password }}</td>
                    <td>{{ user.status }}</td>
                    <td>{{ user.created_at }}</td>
                    <td><a href="/admin_login/user_edit/{{ user.id }}" class="btn btn-primary">Edit</a></td>
                    <td><a href="/admin_login/user_delete/{{ user.id }}" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#bootstrapdatatable').DataTable({
                "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
                "iDisplayLength": 3
            }
            );
        });
    </script>

</body>

</html>

templates/admin_templates/session_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Edit Session</title>
</head>

<body>
    <center>
        <h1>Edit Session</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_subject">Subject:</label>
            <input type="text" id="id_subject" name="subject" value="{{ form.subject.value }}">
            <br><br>
            <label for="id_date">Date:</label>
            <input type="date" id="id_date" name="date" value="{{ form.date.value }}">
            <br><br>
            <label for="id_time">Time:</label>
            <input type="time" id="id_time" name="time" value="{{ form.time.value }}">
            <br><br>
            <button type="submit">Save Session</button>
        </form>
        
    </center>
</body>

</html>

templates/admin_templates/user_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Edit User</title>
</head>

<body>
    <center>
        <h1>Edit User</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- Render form fields -->
            <button type="submit">Save Changes</button>
        </form>
    </center>
</body>

</html>